### PR TITLE
Do not mark class as final to allow overrides.

### PR DESCRIPTION
**Pull request by NikoGrano**

### CODE REVIEW

**Comment by NikoGrano** [comment]
@RikudouSage Sorry for ping, but would you mind taking a look?

**Comment by RikudouSage** [comment]
Hi, sorry for the late reply, can you explain why would you want to do that? Extending non-abstract classes is not generally considered best practice, if you tell me why you want that maybe we'll find some solution to that problem.

**Comment by NikoGrano** [comment]
NP. I'm extending this to have support for some "not standard following" Finnish banks. Some of it is still custom, while they are moving to EU standards. So, I extended this class to make it work, without copy-pasting full class. (I would like to avoid maintaining copy-pasted code.)

I like the concept keeping classes as final, but in libraries with multiple different use cases, its just not possible. Other option if you want, you could create abstract base library which EU, SZ, CZ, libraries would extend. In that case, I could just use that base library and then create my own implementation for these banks who are not following the standard.

**Comment by RikudouSage** [comment]
It would be much better to add support for some configuration object, I don't really want to make the class extendable, that would mean I cannot break any of the protected methods in addition to the public ones to not break backwards compatibility.

**Comment by NikoGrano** [comment]
What's your idea? I need to push this into production anyways soon.

I'm currently overriding these parts:

https://github.com/RikudouSage/QrPaymentEU/blob/f74b97ea4baae7aa22896e3b4e65d6f98c6dfe36/src/QrPayment.php#L321-L331

Replaced with 
```php
        $result[] = 'BCD'; // the service tag
        $result[] = '001'; // version
        $result[] = $this->getCharacterSet();
        $result[] = 'SCT'; // identification
        $result[] = $this->getBic();
        $result[] = $this->getBeneficiaryName();
        $result[] = $this->getIban()->asString();
        $result[] = $this->getAmount() ? $this->getCurrency() . number_format($this->getAmount(), 2) : '';
        $result[] = $this->getPurpose();
        $result[] = $this->getRemittanceText();
        $result[] = $this->getInformation();
        $result[] = 'ReqdExctnDt/'.$this->getDueDate()->format('Y-m-d');
```

https://github.com/RikudouSage/QrPaymentEU/blob/f74b97ea4baae7aa22896e3b4e65d6f98c6dfe36/src/QrPayment.php#L379-L387

And well, this is replaced with implementation...

**Comment by RikudouSage** [comment]
Please check if #40 would fix your issue.

**Pull request closed without merging**
